global using Autodesk.AutoCAD.ApplicationServices;
global using Autodesk.AutoCAD.Colors;
global using Autodesk.AutoCAD.DatabaseServices;
global using Autodesk.AutoCAD.EditorInput;
global using Autodesk.AutoCAD.Geometry;
global using Autodesk.AutoCAD.GraphicsInterface;
global using Autodesk.AutoCAD.Runtime;
global using IFoxCAD.Basal;
global using IFoxCAD.Cad;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text.RegularExpressions;
global using System.Windows.Forms;
global using Acap = Autodesk.AutoCAD.ApplicationServices.Application;
global using Color = Autodesk.AutoCAD.Colors.Color;
global using Exception = System.Exception;
global using Polyline = Autodesk.AutoCAD.DatabaseServices.Polyline;
global using Viewport = Autodesk.AutoCAD.DatabaseServices.Viewport;
global using WorldDraw = Autodesk.AutoCAD.GraphicsInterface.WorldDraw;
global using GB_NewCadPlus_LM;

