//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB_NewCadPlus_IV {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB_NewCadPlus_IV.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _00_脱硫系统计算_总表 {
            get {
                object obj = ResourceManager.GetObject("_00_脱硫系统计算_总表", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _00_计算总表_公式导出 {
            get {
                object obj = ResourceManager.GetObject("_00_计算总表_公式导出", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_220V用电设备点或配电柜 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_220V用电设备点或配电柜", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_380V用电设备大于10KW {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_380V用电设备大于10KW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_380V用电设备点或配电柜 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_380V用电设备点或配电柜", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_UPS16A插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_UPS16A插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_UPS插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_UPS插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_三点互锁 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_三点互锁", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_三相380V插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_三相380V插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_三相岛型插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_三相岛型插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_三相潮湿插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_三相潮湿插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_三联插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_三联插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_两点互锁 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_两点互锁", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_互锁插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_互锁插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_传递窗电源插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_传递窗电源插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相16A三孔插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相16A三孔插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相20A三孔插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相20A三孔插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相25A三孔插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相25A三孔插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相32A三孔插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相32A三孔插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相三孔岛型插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相三孔岛型插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相三孔插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相三孔插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相五孔岛型插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相五孔岛型插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相地面插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相地面插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相夹层插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相夹层插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相空调插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相空调插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_单相防爆岛型插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_单相防爆岛型插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_厨宝安全型插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_厨宝安全型插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_厨宝电热水器安全型插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_厨宝电热水器安全型插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_四联插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_四联插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_地面插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_地面插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_壁挂空调插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_壁挂空调插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_实验台UPS功能柱插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_实验台UPS功能柱插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_实验台UPS功能柱电源 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_实验台UPS功能柱电源", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_实验台上方220V插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_实验台上方220V插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_实验台功能柱插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_实验台功能柱插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_带保护极的三相密闭插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_带保护极的三相密闭插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_带保护极的三相暗敷插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_带保护极的三相暗敷插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_带保护极的三相防爆插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_带保护极的三相防爆插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_带保护极的单相密闭插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_带保护极的单相密闭插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_带保护极的单相暗敷插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_带保护极的单相暗敷插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_带保护极的单相防爆插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_带保护极的单相防爆插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_应急16A插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_应急16A插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_应急插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_应急插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_手消毒插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_手消毒插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_插座箱 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_插座箱", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_潮湿插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_潮湿插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_灭蝇灯插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_灭蝇灯插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_灭蝇灯插座_底边 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_灭蝇灯插座_底边", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_烘手器 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_烘手器", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_烘手器插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_烘手器插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_用电设备点或配电柜 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_用电设备点或配电柜", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_电热水器安全型插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_电热水器安全型插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_空调插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_空调插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_立式空调插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_立式空调插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_红外感应门插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_红外感应门插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_视孔灯 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_视孔灯", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_设备用电点位 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_设备用电点位", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_门禁插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_门禁插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DQTJ_EQUIP_驱鼠器插座 {
            get {
                object obj = ResourceManager.GetObject("DQTJ_EQUIP_驱鼠器插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DUCT_风口_F1_600x1200_TCH {
            get {
                object obj = ResourceManager.GetObject("DUCT-风口_F1_600x1200_TCH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DUCT_风口_F2_900x600_TCH {
            get {
                object obj = ResourceManager.GetObject("DUCT-风口_F2_900x600_TCH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DUCT_风口_F3_600x600_TCH {
            get {
                object obj = ResourceManager.GetObject("DUCT-风口_F3_600x600_TCH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DUCT_风口_F4_900x1200_TCH {
            get {
                object obj = ResourceManager.GetObject("DUCT-风口_F4_900x1200_TCH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap GB_LOGO {
            get {
                object obj = ResourceManager.GetObject("GB_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap GB_LOGO_02 {
            get {
                object obj = ResourceManager.GetObject("GB_LOGO_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] GB_PID_FL_法兰 {
            get {
                object obj = ResourceManager.GetObject("GB_PID_FL_法兰", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] GB_PID_FMDF_蝶阀 {
            get {
                object obj = ResourceManager.GetObject("GB_PID_FMDF_蝶阀", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] GB_PID_GDJK_出口管道 {
            get {
                object obj = ResourceManager.GetObject("GB_PID_GDJK_出口管道", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] GB_PID_GDJK_进口管道 {
            get {
                object obj = ResourceManager.GetObject("GB_PID_GDJK_进口管道", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] GB_PID_YJJG_异径接管 {
            get {
                object obj = ResourceManager.GetObject("GB_PID_YJJG_异径接管", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_冷不带压直排 {
            get {
                object obj = ResourceManager.GetObject("PTJ_冷不带压直排", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_冷直排管 {
            get {
                object obj = ResourceManager.GetObject("PTJ_冷直排管", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_地漏 {
            get {
                object obj = ResourceManager.GetObject("PTJ_地漏", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_大便器给水 {
            get {
                object obj = ResourceManager.GetObject("PTJ_大便器给水", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_大洗涤池_1_2x0_5m {
            get {
                object obj = ResourceManager.GetObject("PTJ_大洗涤池_1_2x0_5m", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_大洗涤池_1_5x0_5m {
            get {
                object obj = ResourceManager.GetObject("PTJ_大洗涤池_1_5x0_5m", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_大洗涤池_1_8x0_5m {
            get {
                object obj = ResourceManager.GetObject("PTJ_大洗涤池_1_8x0_5m", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_大洗涤池_1x0_5m {
            get {
                object obj = ResourceManager.GetObject("PTJ_大洗涤池_1x0_5m", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_大洗涤池_2_0x0_5m {
            get {
                object obj = ResourceManager.GetObject("PTJ_大洗涤池_2_0x0_5m", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_小便器给水 {
            get {
                object obj = ResourceManager.GetObject("PTJ_小便器给水", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_拖布池 {
            get {
                object obj = ResourceManager.GetObject("PTJ_拖布池", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_水池给水 {
            get {
                object obj = ResourceManager.GetObject("PTJ_水池给水", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_洗涤盆 {
            get {
                object obj = ResourceManager.GetObject("PTJ_洗涤盆", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_洗眼器 {
            get {
                object obj = ResourceManager.GetObject("PTJ_洗眼器", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_洗脸盆 {
            get {
                object obj = ResourceManager.GetObject("PTJ_洗脸盆", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_热不带压直排 {
            get {
                object obj = ResourceManager.GetObject("PTJ_热不带压直排", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_热直排管 {
            get {
                object obj = ResourceManager.GetObject("PTJ_热直排管", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PTJ_给水点 {
            get {
                object obj = ResourceManager.GetObject("PTJ_给水点", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] STJ_受力点 {
            get {
                object obj = ResourceManager.GetObject("STJ_受力点", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_互联网插座 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_互联网插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_人像识别器 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_人像识别器", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_人脸识别一体机 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_人脸识别一体机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_内线电话插座 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_内线电话插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_半球彩色摄像机 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_半球彩色摄像机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_吸顶式无线AP {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_吸顶式无线AP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_外线电话插座 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_外线电话插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_安防监控 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_安防监控", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_室外彩色云台摄像机 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_室外彩色云台摄像机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_室外彩色摄像机 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_室外彩色摄像机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_局域网插座 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_局域网插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_带扬声器电话机 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_带扬声器电话机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_广角彩色摄像机 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_广角彩色摄像机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_无线AP {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_无线AP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_电控锁 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_电控锁", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_电话插座 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_电话插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_电话网络插座 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_电话网络插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_电锁按键 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_电锁按键", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_监控文字 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_监控文字", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_眼纹识别器 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_眼纹识别器", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_网络交换机 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_网络交换机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_网络插座 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_网络插座", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_读卡器 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_读卡器", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_门磁开关 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_门磁开关", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_门禁控制器 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_门禁控制器", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_防爆型电话机 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_防爆型电话机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ZKTJ_EQUIP_防爆型网络摄像机 {
            get {
                object obj = ResourceManager.GetObject("ZKTJ_EQUIP_防爆型网络摄像机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 上 {
            get {
                object obj = ResourceManager.GetObject("上", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 下 {
            get {
                object obj = ResourceManager.GetObject("下", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 右 {
            get {
                object obj = ResourceManager.GetObject("右", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 右上 {
            get {
                object obj = ResourceManager.GetObject("右上", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 右下 {
            get {
                object obj = ResourceManager.GetObject("右下", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 左 {
            get {
                object obj = ResourceManager.GetObject("左", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 左上 {
            get {
                object obj = ResourceManager.GetObject("左上", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 左下 {
            get {
                object obj = ResourceManager.GetObject("左下", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
